# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on:
  workflow_call:
    # Map the inputs that the caller needs to provide
    inputs:
      java_version:
        description: "The Java version to use to compile. Default: 21"
        required: false
        type: string
        default: "21" # Java 21 is the default
      build_command:
        description: "The build command to use. Default: mvn"
        required: false
        type: string
        default: "mvn -B -V clean install"
      fetch_all_commits:
        description: "Whether to fetch all commits. Default: false"
        required: false
        type: boolean
        default: false
      maven_version:
        description: "The Maven version to use. Defaults to version of the runner image"
        required: false
        type: string
        # Can't have dynamic default of the current version of Maven in the runner so hard-code it.
        default: "3.9.14"

# cancel in-progress runs of the same workflow
# to avoid unnecessary runs when multiple commits pushed
# in a short period of time
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: ${{ inputs.fetch_all_commits == true && '0' || '1' }}
          persist-credentials: false

      - uses: project-ncl/shared-github-actions/.github/actions/maven-build@94481b379fd7ddda5fe363d1c1d5fc311930c607 # main
        with:
          java_version: ${{ inputs.java_version }}
          build_command: ${{ inputs.build_command }}
          maven_version: ${{ inputs.maven_version }}

      - name: Check for wrong code formatting
        run: |
          if [[ -n $(git status --porcelain) ]]; then
              echo "Code formatting errors"
              echo "----------------------"
              git diff
              exit 1
          fi
