# This is not meant to be copied and is only for this repository.
name: Validate GitHub Actions Workflows for this shared actions repo
permissions: {}

on:
  pull_request:
    paths:
      - '.github/workflows/*.yml'

jobs:

  validate:
    uses: ./.github/workflows/validate-gh-action.yml
